In [ ]:
#Traffic PINN 1D test
#Check point 
#Import libraries



In [1]:
import numpy as np
import matplotlib as plt


In [7]:
# Craete 2D mesh Grid
#1. initialise x array
#2. initialise t array
#3. use meshgrid to create 2D mesh
N_x = 200
start_length = 0
end_length = 10 #(km)
N_t = 500
start_time = 0
end_time = 0.25#(hr)



arr_x = np.linspace(start_length, end_length, N_x)
arr_t = np.linspace(start_time, end_time, N_t)

X_grid, T_grid = np.meshgrid(arr_x, arr_t)
print (X_grid, T_grid)
#plot grid

[[ 0.          0.05025126  0.10050251 ...  9.89949749  9.94974874
  10.        ]
 [ 0.          0.05025126  0.10050251 ...  9.89949749  9.94974874
  10.        ]
 [ 0.          0.05025126  0.10050251 ...  9.89949749  9.94974874
  10.        ]
 ...
 [ 0.          0.05025126  0.10050251 ...  9.89949749  9.94974874
  10.        ]
 [ 0.          0.05025126  0.10050251 ...  9.89949749  9.94974874
  10.        ]
 [ 0.          0.05025126  0.10050251 ...  9.89949749  9.94974874
  10.        ]] [[0.       0.       0.       ... 0.       0.       0.      ]
 [0.000501 0.000501 0.000501 ... 0.000501 0.000501 0.000501]
 [0.001002 0.001002 0.001002 ... 0.001002 0.001002 0.001002]
 ...
 [0.248998 0.248998 0.248998 ... 0.248998 0.248998 0.248998]
 [0.249499 0.249499 0.249499 ... 0.249499 0.249499 0.249499]
 [0.25     0.25     0.25     ... 0.25     0.25     0.25    ]]


In [6]:
# 1. Base traffic density of 30 everywhere along the 200 spatial points
rho_0 = np.ones(N_x) * 30.0 #30vehicles /km
# 2. Define the traffic jam bump parameters
amplitude = 90.0  # Spikes the density from 30 up to 120 (30 + 90 = 120)
center = 4.0      # Centered at x = 4 km
spread = 1.0      # How wide the traffic jam stretches

# 3. Add the bell-shaped traffic jam to our baseline
# np.exp() computes e^x. When arr_x is exactly at the center (4.0), 
# this exponential term equals 1, giving us our maximum peak.
rho_0 += amplitude * np.exp(-((arr_x - center) / spread)**2)

print(rho_0)



[ 30.00001013  30.0000151   30.0000224   30.00003307  30.00004857
  30.00007097  30.00010318  30.00014926  30.00021482  30.00030762
  30.0004383   30.00062134  30.00087639  30.00122991  30.00171733
  30.00238583  30.00329787  30.00453559  30.00620642  30.00844997
  30.01144657  30.01542775  30.02068885  30.02760429  30.03664575
  30.04840355  30.06361178  30.08317724  30.10821266  30.14007425
  30.1804036   30.23117387  30.2947399   30.37389165  30.47191008
  30.5926242   30.74046778  30.92053351  31.13862229  31.4012848
  31.71585186  32.09045016  32.53399932  33.05618626  33.66741277
  34.37871235  35.20163277  36.1480814   37.23013121  38.4597864
  39.84870809  41.40790201  43.14737189  45.07574427  47.19987241
  49.52442882  52.05149808  54.78018298  57.70623847  60.82174875
  64.11486309  67.56960582  71.16577473  74.87894062  78.68055817
  82.53819531  86.41588443  90.2745949   94.07282141  97.76727857
 101.31368713 104.66763335 107.78547893 110.62529613 113.14780032
 115.3172512

In [9]:
v_max = 100 #(km/hr)

rho_max = 150 #(cars/km)




arr_q = rho_0*v_max *(1-(rho_0/rho_max))

print (arr_q)

[2400.00060769 2400.0009061  2400.00134424 2400.00198419 2400.00291406
 2400.00425813 2400.00619078 2400.00895529 2400.01288902 2400.01845723
 2400.02629783 2400.03728031 2400.05258302 2400.07379342 2400.10303762
 2400.14314617 2400.19786507 2400.27212198 2400.37235969 2400.50695053
 2400.68670708 2400.92550625 2401.24104538 2401.6557495  2402.19784966
 2402.90265128 2403.81400909 2404.98602184 2406.48495298 2408.39137465
 2410.80251915 2413.83480462 2417.62647954 2422.34030237 2428.16613857
 2435.32331667 2444.06253873 2454.66708903 2467.45303022 2482.76802189
 2500.98834644 2522.51368815 2547.75919061 2577.14432587 2611.07815525
 2649.94065973 2694.05997714 2743.68561418 2798.95800783 2859.87519336
 2926.25778472 2997.71396837 3073.60672153 3153.02594617 3234.76860412
 3317.3301821  3398.91083977 3477.43933313 3550.61720816 3615.98479433
 3671.00919632 3713.19282822 3740.19914439 3749.99022975 3740.96899436
 3712.11707436 3663.11838846 3594.45783382 3507.48498893 3404.43401766
 3288.